---
language: python
services: docker

env:
  global:
    - REPO_NAME: ansible-role-sshd-lockdown
    - ROLE_NAME: davidalger.sshd_lockdown

  matrix:
    - MOLECULE_DISTRO: centos7

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $REPO_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
